apiVersion: apps/v1
kind: Deployment
metadata:
  name: worldwave-radio
  namespace: worldwave-radio

spec:
  replicas: 1

  selector:
    matchLabels:
      app: worldwave-radio

  template:
    metadata:
      labels:
        app: worldwave-radio

    spec:
      containers:
        - name: worldwave-radio
          image: bleosas/devsecops-app:version5
          imagePullPolicy: Always

          ports:
            - containerPort: 8080
              name: http
