apiVersion: v1
kind: Service
metadata:
  name: worldwave-radio
  namespace: worldwave-radio
spec:
  type: LoadBalancer
  selector:
    app: worldwave-radio
  ports:
    - name: http
      port: 8082
      targetPort: 8080
